apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster-2
  region: us-east-1

managedNodeGroups:
  - name: app-group
    instanceType: t2.medium
    desiredCapacity: 3
    volumeSize: 20
