apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: nodeGroup1
    instanceType: t2.medium
    desiredCapacity: 3
    volumeSize: 20
