apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster-1
  region: us-east-1

nodeGroups:
  - name: app-group
    instanceType: t2.medium
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
