apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksClusterSn
  region: us-east-2

nodeGroups:
  - name: nodeGroup2
    instanceType: t2.medium
    desiredCapacity: 3
    volumeSize: 80
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
    ssh:
      allow: true
